name: apexo
description: "Dental Clinic Management System"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  fluent_ui: ^4.4.0
  hive_flutter: ^1.1.0
  modal_bottom_sheet: ^3.0.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  table_calendar: ^3.1.2
  logging: ^1.2.0
  camerawesome: ^2.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  mime: ^1.0.6
  fl_chart: ^0.69.0
  pocketbase: ^0.18.1
  file_picker: ^8.1.3
  qr_flutter: ^4.1.0
  printing: ^5.13.4
  pdf: ^3.11.1
  bidi: ^2.0.12
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/logo.png
    - assets/images/missing.png
    - assets/fonts/readex.ttf
    - assets/fonts/readex-bold.ttf